server:
  port: 8905

spring:
  mqtt:
    username: 4c5ca5b7-a6bb-4ca3-a0eb-a41e2e68c99e
    password: ea5bdb86-275d-4981-906b-9845b0b034a4
    url: tcp://121.41.1.169:1883
    client:
      id: PumpController_20191014_1
    default:
      topic: topic
    completionTimeout: 3000

influx:
  url: http://121.41.1.169:8086
  user: mainflux
  password: mainflux
  database: mainflux

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%-20thread] %-5level [%-42logger{36}] - %msg%n"
    file:    "%d{yyyy-MM-dd HH:mm:ss} [%-20thread] %-5level [%-42logger{36}] - %msg%n"
  file: E:\NIT_G\log.log

mqtt:
  broker: tcp://121.41.1.169:1883
  userName: 4c5ca5b7-a6bb-4ca3-a0eb-a41e2e68c99e
  passWord: ea5bdb86-275d-4981-906b-9845b0b034a4
  clientId: PumpController

